version: '3.7'

services:
  bot:
    image: ${CONTAINER_IMAGE}-bot:${CI_COMMIT_SHORT_SHA}
    env_file: /home/tavern-keeper/host-files/.env
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:12.3-alpine
    env_file: /home/tavern-keeper/host-files/.env
    ports:
      - '5432:5432'
    volumes:
      - /home/tavern-keeper/host-files/postgres-data:/var/lib/postgresql/data
    restart: always
  ui:
    image: ${CONTAINER_IMAGE}-ui:${CI_COMMIT_SHORT_SHA}
    env_file: /home/tavern-keeper/host-files/.env
    depends_on:
      - postgres
      - api
    ports:
      - '80:80'
    restart: always
  api:
    image: ${CONTAINER_IMAGE}-api:${CI_COMMIT_SHORT_SHA}
    env_file: /home/tavern-keeper/host-files/.env
    ports:
      - '3002:3002'
    restart: always
