version: '3.7'

services:
  bot:
    build: ./bot
    command: nodemon ./src
    volumes:
      - ./bot:/app
    env_file: .env
  postgres:
    image: postgres:12.3-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    env_file: .env
