version: '3.7'

services:
  bot:
    image: ${CONTAINER_IMAGE}-bot:${CI_COMMIT_SHORT_SHA}
    env_file: /home/tavern-keeper/host-files/.env
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 60s
  postgres:
    image: postgres:12.3-alpine
    env_file: /home/tavern-keeper/host-files/.env
    ports:
      - '5432:5432'
    volumes:
      - /home/tavern-keeper/host-files/postgres-data:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 60s
  ui:
    image: ${CONTAINER_IMAGE}-ui:${CI_COMMIT_SHORT_SHA}
    env_file: /home/tavern-keeper/host-files/.env
    depends_on:
      - postgres
      - api
    ports:
      - '80:80'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 60s
  api:
    image: ${CONTAINER_IMAGE}-api:${CI_COMMIT_SHORT_SHA}
    env_file: /home/tavern-keeper/host-files/.env
    ports:
      - '3002:3002'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 60s
